In [ ]:
import pandas as pd

In [ ]:
airbnb = pd.read_csv("sample_airbnb.listingsAndReviews.csv")

<ipython-input-17-4cc214446487>:1: DtypeWarning: Columns (0,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,122,123,124,136,137,138,148,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,2458,2459,2460,2461,2462,2463,2464,2465,2466,2467,2468,2469,2470,2471,2472,2473,2474,2475,2476,2477,2478,2479,2480,2481,2482,2483,2484,2485,2486,2487,2488,2489,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500,2501,2502,2503,2504,2505,2506,2507,2508,2509,2510,2511,2512,2513,2514,2515,2516,2517,2518,2519,2520,2521,2522,2523,2524,2525,2526,2527,2528,2529,2530,2531,2532,2533,2534,2535,2536,2537,2538,2539,2540,2541,2542,2543,2544,2545,2546,2547,2548,2549,2550,2551,2552,2553,2554,2555,2556,2557,2558,2559,2560,2561,2562,2563,2564,2565,2566,2567,2568,2569,2570,2571,2572,2573,2574,2575,2576,2577,2578,2579,2580,2581,2582,2583,2584,2585,2586,2587,2588,2589,2590,2591,2592,2593,2594,2595,2596,2597,2598,2599,2600,2601,2602,2603,2604,2605,2606,2607,2608,2609,2610,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2624,2625,2626,2627,2628,2629,2630,2631,2632,2633,2634,2635,2636,2637,2638,2639,2640,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,2660,2661,2662,2663,2664,2665,2666,2667,2668,2669,2670,2671,2672,2673,2674,2675,2676,2677,2678,2679,2680,2681,2682,2683,2684,2685,2686,2687,2688,2689,2690,2691,2692,2693,2694,2695,2696,2697,2698,2699,2700,2701,2702,2703,2704,2705,2706,2707,2708,2709,2710,2711,2712,2713,2714,2715,2716,2717,2718,2719,2720,2721,2722,2723,2724,2725,2726,2727,2728,2729,2730,2731,2732,2733,2734,2735,2736,2737,2738,2739,2740,2741,2742,2743,2744,2745,2746,2747,2748,2749,2750,2751,2752,2753,2754,2755,2756,2757,2758,2759,2760,2761,2762,2763,2764,2765,2766,2767,2768,2769,2770,2771,2772,2773,2774,2775,2776,2777,2778,2779,2780,2781,2782,2783,2784,2785,2786,2787,2788,2789,2790,2791,2792,2793,2794,2795,2796,2797,2798,2799,2800,2801,2802,2803,2804,2805,2806,2807,2808,2809,2810,2811,2812,2813,2814,2815,2816,2817,2818,2819,2820,2821,2822,2823,2824,2991,2992,2993,2994,2995,2996,2997,2998,2999,3000,3001,3002,3003,3004,3005,3006,3007,3008,3009,3010,3011,3012,3013,3014,3015,3016,3017,3018,3019,3020,3021,3022,3023,3024,3025,3026,3027,3028,3029,3030,3031,3032,3033,3034,3035,3036,3037,3038,3039,3040,3041,3042,3043,3044,3045,3046,3047,3048,3049,3050,3051,3052,3053,3054,3055,3056,3057,3058,3059,3060,3061,3062,3063,3064,3065,3066,3067,3068,3069,3070,3071,3072,3073,3074,3075,3076,3077,3078,3079,3080,3081,3082,3083,3084,3085,3086,3087,3088,3089,3090,3091,3092,3093,3094,3095,3096,3097,3098,3099,3100,3101,3102,3103,3104,3105,3106,3107,3108,3109,3110,3111,3112,3113,3114,3115,3116,3117,3118,3119,3120,3121,3122,3123,3124,3125,3126,3127,3128,3129,3130,3131,3132,3133,3134,3135,3136,3137,3138,3139,3140,3141,3142,3143,3144,3145,3146,3147,3148,3149,3150,3151,3152,3153,3154,3155,3156,3157,3158,3159,3160,3161,3162,3163,3164,3165,3166,3167,3168,3169,3170,3171,3172,3173,3174,3175,3176,3177,3178,3179,3180,3181,3182,3183,3184,3185,3186,3187,3188,3189,3190,3191,3192,3193,3194,3195,3196,3197,3198,3199,3200,3201,3202,3203,3204,3205,3206,3207,3208,3209,3210,3211,3212,3213,3214,3215,3216,3217,3218,3219,3220,3221,3222,3223,3224,3225,3226,3227,3228,3229,3230,3231,3232,3233,3234,3235,3236,3237,3238,3239,3240,3241,3242,3243,3244,3245,3246,3247,3248,3249,3250,3251,3252,3253,3254,3255,3256,3257,3258,3259,3260,3261,3262,3263,3264,3265,3266,3267,3268,3269,3270,3271,3272,3273,3274,3275,3276,3277,3278,3279,3280,3281,3282,3283,3284,3285,3286,3287,3288,3289,3290,3291,3292,3293,3294,3295,3296,3297,3298,3299,3300,3301,3302,3303,3304,3305,3306,3307,3308,3309,3310,3311,3312,3313,3314,3315,3316,3317,3318,3319,3320,3321,3322,3323,3324,3325,3326,3327,3328,3329,3330,3331,3332,3333,3334,3335,3336,3337,3338,3339,3340,3341,3342,3343,3344,3345,3346,3347,3348,3349,3350,3351,3352,3353,3354,3355,3356,3357) have mixed types. Specify dtype option on import or set low_memory=False.
  airbnb = pd.read_csv("sample_airbnb.listingsAndReviews.csv")

In [ ]:
airbnb.shape

(5557, 3361)

In [ ]:
airbnb.head()

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,reviews[526].comments,reviews[527].comments,reviews[528].comments,reviews[529].comments,reviews[530].comments,reviews[531].comments,reviews[532].comments,weekly_price,monthly_price,reviews_per_month
0,10006546,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,Privileged views of the Douro River and Ribeir...,Fantastic duplex apartment with three bedrooms...,"In the neighborhood of the river, you can find...",Lose yourself in the narrow streets and stairc...,Transport: • Metro station and S. Bento railwa...,We are always available to help guests. The ho...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10009999,https://www.airbnb.com/rooms/10009999,Horto flat with small garden,One bedroom + sofa-bed in quiet and bucolic ne...,Lovely one bedroom + sofa-bed in the living ro...,One bedroom + sofa-bed in quiet and bucolic ne...,This charming ground floor flat is located in ...,"There´s a table in the living room now, that d...","Easy access to transport (bus, taxi, car) and ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1492.0,4849.0,NaN
2,1001265,https://www.airbnb.com/rooms/1001265,Ocean View Waikiki Marina w/prkg,A short distance from Honolulu's billion dolla...,Great studio located on Ala Moana across the s...,A short distance from Honolulu's billion dolla...,You can breath ocean as well as aloha.,NaN,Honolulu does have a very good air conditioned...,"Pool, hot tub and tennis",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,650.0,2150.0,NaN
3,10021707,https://www.airbnb.com/rooms/10021707,Private Room in Bushwick,Here exists a very cozy room for rent in a sha...,NaN,Here exists a very cozy room for rent in a sha...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Quarto com vista para a Lagoa Rodrigo de Freit...,NaN,Quarto com vista para a Lagoa Rodrigo de Freit...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
airbnb.tail()

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,reviews[526].comments,reviews[527].comments,reviews[528].comments,reviews[529].comments,reviews[530].comments,reviews[531].comments,reviews[532].comments,weekly_price,monthly_price,reviews_per_month
5552,9987200,https://www.airbnb.com/rooms/9987200,The best suite in Copacabana (total privacy),Excellent private suite with bathroom at the A...,"Beautiful suite with two beds, fridge, cable T...",Excellent private suite with bathroom at the A...,Copacabana beach is located in a district of t...,El aparcamiento puede ser utilizado a través ...,"El Apart está muy bien comunicado con metro, a...",The check in time is after 2 PM and check out ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5553,9990304,https://www.airbnb.com/rooms/9990304,March Madness Special! Aina Nalu Platinum D107,Walk out to Saltwater Infinity Pool! Call us N...,We invite you to come and stay in our upgraded...,Walk out to Saltwater Infinity Pool! Call us N...,-Located in the heart of Lahaina town and a sh...,Onsite parking at Aina Nalu is available for $...,You can walk to most attractions within Lahain...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5554,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Relax Hawaiian Style in Gated Community on Oce...,"***NOTE: THE OCEAN INFINITY POOL (""POOL 1""0 WI...",Relax Hawaiian Style in Gated Community on Oce...,Location: Located at the south end of Lahaina ...,Puamana Resort requires a $10/day resort fee w...,You can walk to most attractions within Lahain...,Guests will have access to the 3 pools in the ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5555,64e636d796106be00d03fb46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5556,64e63ae32b568f52b3fe22d0,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,Privileged views of the Douro River and Ribeir...,Fantastic duplex apartment with three bedrooms...,"In the neighborhood of the river, you can find...",Lose yourself in the narrow streets and stairc...,Transport: • Metro station and S. Bento railwa...,We are always available to help guests. The ho...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
airbnb.columns

Index(['_id', 'listing_url', 'name', 'summary', 'space', 'description',
       'neighborhood_overview', 'notes', 'transit', 'access',
       ...
       'reviews[526].comments', 'reviews[527].comments',
       'reviews[528].comments', 'reviews[529].comments',
       'reviews[530].comments', 'reviews[531].comments',
       'reviews[532].comments', 'weekly_price', 'monthly_price',
       'reviews_per_month'],
      dtype='object', length=3361)

In [ ]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5557 entries, 0 to 5556
Columns: 3361 entries, _id to reviews_per_month
dtypes: float64(1634), object(1727)
memory usage: 142.5+ MB

In [ ]:
airbnb.describe()

,minimum_nights,maximum_nights,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,security_deposit,cleaning_fee,...,reviews[526].reviewer_id,reviews[527].reviewer_id,reviews[528].reviewer_id,reviews[529].reviewer_id,reviews[530].reviewer_id,reviews[531].reviewer_id,reviews[532].reviewer_id,weekly_price,monthly_price,reviews_per_month
count,5556.000000,5.556000e+03,5556.000000,5551.000000,5543.000000,5556.000000,5546.000000,5556.000000,3472.000000,4025.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,714.000000,656.000000,94.000000
mean,5.563715,1.382527e+06,3.506659,1.411998,2.071983,27.610691,1.291111,278.730382,509.341302,94.060124,...,27496304.0,34351862.0,223695571.0,31351265.0,33503139.0,188362368.0,55764067.0,1530.903361,5391.370427,1.712766
std,22.611876,5.256447e+07,2.297604,1.042067,1.619992,49.794882,0.702212,842.143942,1594.584218,110.194022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3185.916331,12723.569651,1.492795
min,1.000000,1.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,0.000000,...,27496304.0,34351862.0,223695571.0,31351265.0,33503139.0,188362368.0,55764067.0,60.000000,250.000000,1.000000
25%,1.000000,5.825000e+01,2.000000,1.000000,1.000000,1.000000,1.000000,70.000000,0.000000,23.000000,...,27496304.0,34351862.0,223695571.0,31351265.0,33503139.0,188362368.0,55764067.0,480.250000,1505.250000,1.000000
50%,2.000000,1.125000e+03,3.000000,1.000000,2.000000,5.000000,1.000000,129.000000,200.000000,60.000000,...,27496304.0,34351862.0,223695571.0,31351265.0,33503139.0,188362368.0,55764067.0,800.000000,2800.000000,1.000000
75%,3.000000,1.125000e+03,4.000000,2.000000,3.000000,32.000000,1.000000,280.000000,500.000000,129.000000,...,27496304.0,34351862.0,223695571.0,31351265.0,33503139.0,188362368.0,55764067.0,1575.250000,4800.000000,2.000000
max,1250.000000,2.147484e+09,16.000000,20.000000,25.000000,533.000000,16.000000,48842.000000,39228.000000,2000.000000,...,27496304.0,34351862.0,223695571.0,31351265.0,33503139.0,188362368.0,55764067.0,59123.000000,253384.000000,10.000000

In [ ]:
 airbnb.dropna(axis=1,how='all')

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,reviews[526].comments,reviews[527].comments,reviews[528].comments,reviews[529].comments,reviews[530].comments,reviews[531].comments,reviews[532].comments,weekly_price,monthly_price,reviews_per_month
0,10006546,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,Privileged views of the Douro River and Ribeir...,Fantastic duplex apartment with three bedrooms...,"In the neighborhood of the river, you can find...",Lose yourself in the narrow streets and stairc...,Transport: • Metro station and S. Bento railwa...,We are always available to help guests. The ho...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10009999,https://www.airbnb.com/rooms/10009999,Horto flat with small garden,One bedroom + sofa-bed in quiet and bucolic ne...,Lovely one bedroom + sofa-bed in the living ro...,One bedroom + sofa-bed in quiet and bucolic ne...,This charming ground floor flat is located in ...,"There´s a table in the living room now, that d...","Easy access to transport (bus, taxi, car) and ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1492.0,4849.0,NaN
2,1001265,https://www.airbnb.com/rooms/1001265,Ocean View Waikiki Marina w/prkg,A short distance from Honolulu's billion dolla...,Great studio located on Ala Moana across the s...,A short distance from Honolulu's billion dolla...,You can breath ocean as well as aloha.,NaN,Honolulu does have a very good air conditioned...,"Pool, hot tub and tennis",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,650.0,2150.0,NaN
3,10021707,https://www.airbnb.com/rooms/10021707,Private Room in Bushwick,Here exists a very cozy room for rent in a sha...,NaN,Here exists a very cozy room for rent in a sha...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Quarto com vista para a Lagoa Rodrigo de Freit...,NaN,Quarto com vista para a Lagoa Rodrigo de Freit...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5552,9987200,https://www.airbnb.com/rooms/9987200,The best suite in Copacabana (total privacy),Excellent private suite with bathroom at the A...,"Beautiful suite with two beds, fridge, cable T...",Excellent private suite with bathroom at the A...,Copacabana beach is located in a district of t...,El aparcamiento puede ser utilizado a través ...,"El Apart está muy bien comunicado con metro, a...",The check in time is after 2 PM and check out ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5553,9990304,https://www.airbnb.com/rooms/9990304,March Madness Special! Aina Nalu Platinum D107,Walk out to Saltwater Infinity Pool! Call us N...,We invite you to come and stay in our upgraded...,Walk out to Saltwater Infinity Pool! Call us N...,-Located in the heart of Lahaina town and a sh...,Onsite parking at Aina Nalu is available for $...,You can walk to most attractions within Lahain...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5554,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Relax Hawaiian Style in Gated Community on Oce...,"***NOTE: THE OCEAN INFINITY POOL (""POOL 1""0 WI...",Relax Hawaiian Style in Gated Community on Oce...,Location: Located at the south end of Lahaina ...,Puamana Resort requires a $10/day resort fee w...,You can walk to most attractions within Lahain...,Guests will have access to the 3 pools in the ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5555,64e636d796106be00d03fb46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5556,64e63ae32b568f52b3fe22d0,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,Privileged views of the Douro River and Ribeir...,Fantastic duplex apartment with three bedrooms...,"In the neighborhood of the river, you can find...",Lose yourself in the narrow streets and stairc...,Transport: • Metro station and S. Bento railwa...,We are always available to help guests. The ho...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN